import './globals.css'
import type { Metadata } from 'next'
import {Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: { children: React.ReactNode, modal: React.ReactNode }) {
  return (
    <html lang="en">
      <body >
      <div className="min-h-full">
      <nav className="bg-gray-50">
    <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div className="flex h-16 items-center justify-between">
        <div className="flex items-center">
          <div className="flex-shrink-0">
            <img className="h-11 w-11" src="/cas.svg"   alt="Your Company"></img>
          </div>
          
        </div>
    
      </div>
    </div>

    
  </nav>
      {props.children}
        {props.modal}
        </div>
        </body>
    </html>
  )
}
